POST http://localhost:8080/park
Content-Type: application/json

{
  "model" : "model",
  "carNumber" : "12",
  "color" : "yellow",
  "amountOfHours" : 2,
  "userId" : 1,
  "address" : "Du"
}

###

GET http://localhost:8080/slots?address=Du

###

POST http://localhost:8080/can-go
Content-Type: application/json

{
  "carNumber" : ""
}
